import type { SpritesheetMetadata } from '@threlte/extras';

export const biomeAtlasMeta = [
  {
    url: '/land-display/empty.png',
    type: 'rowColumn',
    width: 4,
    height: 3,
    animations: [
      { name: 'empty', frameRange: [0, 0] },
      { name: 'default', frameRange: [0, 0] },
      { name: 'empty-outline', frameRange: [0, 0] },
      { name: 'default-outline', frameRange: [0, 0] },
      { name: 'empty_0', frameRange: [0, 0] },
      { name: 'empty_1', frameRange: [1, 1] },
      { name: 'empty_2', frameRange: [2, 2] },
      { name: 'empty_3', frameRange: [3, 3] },
      { name: 'empty_4', frameRange: [4, 4] },
      { name: 'empty_5', frameRange: [5, 5] },
      { name: 'empty_6', frameRange: [6, 6] },
      { name: 'empty_7', frameRange: [7, 7] },
      { name: 'empty_8', frameRange: [8, 8] },
      { name: 'empty_9', frameRange: [9, 9] },
      { name: 'empty_10', frameRange: [10, 10] },
      { name: 'auction_shadow', frameRange: [11, 11] },
    ],
  },
  {
    url: '/tokens/+global/biomes.png',
    type: 'rowColumn',
    width: 4,
    height: 5,
    animations: [
      { name: 'slinky', frameRange: [0, 0] },
      { name: 'auction', frameRange: [1, 1] },
      { name: 'pimp', frameRange: [2, 2] },
      { name: 'paper', frameRange: [3, 3] },
      { name: 'ekubo', frameRange: [4, 4] },
      { name: 'eth', frameRange: [5, 5] },
      { name: 'flip', frameRange: [6, 6] },
      { name: 'lords', frameRange: [7, 7] },
      { name: 'eLORDS', frameRange: [7, 7] },
      { name: 'nftLORDS', frameRange: [7, 7] },
      { name: 'nums', frameRange: [8, 8] },
      { name: 'pal', frameRange: [9, 9] },
      { name: 'circus', frameRange: [10, 10] },
      { name: 'sisters', frameRange: [11, 11] },
      { name: 'btc', frameRange: [12, 12] },
      { name: 'brother', frameRange: [13, 13] },
      { name: 'strk', frameRange: [14, 14] },
      { name: 'nftSTRK', frameRange: [14, 14] },
      { name: 'wnt', frameRange: [15, 15] },
      { name: 'eWNT', frameRange: [15, 15] },
      { name: 'qq', frameRange: [16, 16] },
      { name: 'eQQ', frameRange: [16, 16] },
      { name: 'evreai', frameRange: [17, 17] },
      { name: 'eSG', frameRange: [17, 17] },
    ],
  },
] as const satisfies SpritesheetMetadata;
