import type { SpritesheetMetadata } from '@threlte/extras';

// BUILDING
export const buildingAtlasMeta = [
  {
    url: '/tokens/+global/buildings.png',
    type: 'rowColumn',
    width: 12,
    height: 21,
    animations: [
      { name: 'empty', frameRange: [250, 250] },
      { name: 'empty_1', frameRange: [250, 250] },
      { name: 'empty_2', frameRange: [250, 250] },
      { name: 'empty_3', frameRange: [250, 250] },
      { name: 'auction', frameRange: [250, 250] },
      { name: 'auction_1', frameRange: [250, 250] },
      { name: 'auction_2', frameRange: [250, 250] },
      { name: 'auction_3', frameRange: [250, 250] },

      { name: 'lords_1', frameRange: [0, 0] },
      { name: 'lords_2', frameRange: [12, 12] },
      // { name: 'lords_3', frameRange: [24, 24] },
      { name: 'pal_1', frameRange: [36, 36] },
      { name: 'pal_2', frameRange: [48, 48] },
      { name: 'pal_3', frameRange: [60, 60] },
      { name: 'pimp_1', frameRange: [72, 72] },
      { name: 'pimp_2', frameRange: [84, 84] },
      { name: 'pimp_3', frameRange: [96, 96] },
      { name: 'ekubo_1', frameRange: [108, 108] },
      { name: 'ekubo_2', frameRange: [120, 120] },
      { name: 'ekubo_3', frameRange: [132, 132] },
      { name: 'sisters_1', frameRange: [144, 144] },
      { name: 'sisters_2', frameRange: [156, 156] },
      { name: 'sisters_3', frameRange: [168, 168] },
      { name: 'slinky_1', frameRange: [180, 180] },
      { name: 'slinky_2', frameRange: [192, 192] },
      { name: 'slinky_3', frameRange: [204, 204] },
      { name: 'btc_1', frameRange: [216, 216] },
      { name: 'btc_2', frameRange: [228, 228] },
      { name: 'btc_3', frameRange: [240, 240] },
      { name: 'paper_1', frameRange: [3, 3] },
      { name: 'paper_2', frameRange: [15, 15] },
      { name: 'paper_3', frameRange: [27, 27] },
      { name: 'strk_1', frameRange: [39, 39] },
      { name: 'strk_2', frameRange: [51, 51] },
      // { name: 'strk_3', frameRange: [63, 63] },
      { name: 'brother_1', frameRange: [75, 75] },
      { name: 'brother_2', frameRange: [87, 87] },
      { name: 'brother_3', frameRange: [99, 99] },
      { name: 'eth_1', frameRange: [111, 111] },
      { name: 'eth_2', frameRange: [123, 123] },
      { name: 'eth_3', frameRange: [135, 135] },
      { name: 'circus_1', frameRange: [147, 147] },
      // { name: 'circus_2', frameRange: [159, 159] },
      // { name: 'circus_3', frameRange: [171, 171] },
      { name: 'nums_1', frameRange: [183, 183] },
      { name: 'nums_2', frameRange: [195, 195] },
      { name: 'nums_3', frameRange: [207, 207] },
      { name: 'flip_1', frameRange: [219, 219] },
      { name: 'flip_2', frameRange: [231, 231] },
      { name: 'flip_3', frameRange: [243, 243] },
      { name: 'wnt_1', frameRange: [6, 6] },
      { name: 'wnt_2', frameRange: [18, 18] },
      // { name: 'wnt_3', frameRange: [30, 30] },
      { name: 'qq_1', frameRange: [42, 42] },
      { name: 'qq_2', frameRange: [54, 54] },
      // { name: 'qq_3', frameRange: [66, 66] },
      { name: 'everai_1', frameRange: [9, 9] },
      { name: 'everai_2', frameRange: [21, 21] },
      // { name: 'everai_3', frameRange: [33, 33] },
    ],
  },
  {
    url: '/tokens/lords/3-animated.png',
    type: 'rowColumn',
    width: 20,
    height: 1,
    animations: [{ name: 'lords_3', frameRange: [0, 19] }],
  },
  {
    url: '/tokens/strk/3-animated.png',
    type: 'rowColumn',
    width: 6,
    height: 1,
    animations: [{ name: 'strk_3', frameRange: [0, 5] }],
  },
  {
    url: '/tokens/everai/3-animated.png',
    type: 'rowColumn',
    width: 4,
    height: 2,
    animations: [{ name: 'everai_3', frameRange: [0, 7] }],
  },
  {
    url: '/tokens/wnt/3-animated.png',
    type: 'rowColumn',
    width: 5,
    height: 2,
    animations: [{ name: 'wnt_3', frameRange: [0, 9] }],
  },
  {
    url: '/tokens/qq/3-animated.png',
    type: 'rowColumn',
    width: 4,
    height: 2,
    animations: [{ name: 'qq_3', frameRange: [0, 7] }],
  },
] as const satisfies SpritesheetMetadata;
