[package]
name = "query-tool"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "chrono"] }
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4"
anyhow = "1.0"