default_token = "nftSTRK"

cors_origins = [
    "http://localhost:3000",
    "https://localhost:3000",
    "https://*.ponzi.land",
    "https://play.ponzi.land",
    "https://ponzi.land",
]

[ekubo]
api_url = "https://starknet-mainnet-api.ekubo.org"
core_contract_address = "0x00000005dd3D2F4429AF886cD1a3b08289DBcEa99A294197E9eB43b0e0325b4b"

[starknet]
rpc_url = "http://katana-test:5050"

[torii]
world_address = "0x16a224c5361127863629cbf70b024de90876901af6ac26180ddad1d1a32ccfb"
torii_url = "http://torii-test:8080"

