[world]
name = "Ponzi Land"
description = "The official Dojo Starter guide, the quickest and most streamlined way to get your Dojo Autonomous World up and running. This guide will assist you with the initial setup, from cloning the repository to deploying your world."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "quests_276111064"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "ponzi_land"

[env]
rpc_url = "http://localhost:5050"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"


[writers]
# We need to be a writer to add events...
"ponzi_land" = ["ponzi_land-actions", "ponzi_land-auth", "ponzi_land-config", "ponzi_land-quests"]

[init_call_args]
"ponzi_land-auth" = [
    "0x001c012e0e8408af283483480f18c0f7a313e76012a06b158913d71cc304ba3b", # Verifier
]

"ponzi_land-token_registry" = [
    "6",                                                                  # 6 tokens,
    "0x7d0c0380fc3b999d5726da0c9c2f986b972ba597eafa903e7bcebcd69f28ffd", # pltSTRK
    "0x24b2bb3c4e87c86f85cc3a8bc010b306ba85e41b4182243fd83181d4967f3a0", # pltLORDS
    "0x6b4ebe671407b67e08d59ef2bbac4a2aafb582e73d2392c26b0c8b61476e021", # pltETH
    "0x1268e7ce03a8855a0c99d3fb027c1b0c0b3a272b2c95053aac1489b68d086a7", # pltPAPER
    "0x55b848a9a852ac0d458e77087379107555e43cca77f8774b0c280b8216384", # pltBROTHER
    "0x4c592e94ac516fdb671991c0154deef802a8f5460ed2e8c754ac415e96aecf7", # pltPAL
]

"ponzi_land-config" = [
    "2",                                                                   # Tax rate
    "3600",                                                                  # Base time
    "2",                                                        # Price decrease rate
    "5",                                                                 # Time speed
    "16",                                                               # Max auctions
    "3",                                                      # Max auctions from bid
    "200",                                                                 # Decay rate
    "100000000000000000","0",                                                                # Floor price
    "3",                                               # Liquidity safety multiplier
    "500000000000000000000","0",                                                          # Min auction price
    "10",                                              # Min auction price multiplier
    "436800",                                                           # Auction duration
    "50",                                                             # Scaling factor
    "12000",                                                          # Linear time decay
    "90",                                                                  # Drop rate
    "100",                                                           # Rate denominator
    "5",                                                               # Max circles
    "0",                                                                 # Claim fee
    "0",                                                                   # Buy fee
    "10",                                                      # Quest auction chance
    "1",                                                      # Quest lands enabled
    "0x0417435DE94b6dffE3a22DFa040E7ceb4FB674209e109E9DB4E43dbcc905C640",                                                      # Our contract for fee
    "0x0417435DE94b6dffE3a22DFa040E7ceb4FB674209e109E9DB4E43dbcc905C640",                                                  # Our contract for auction
    "10",                                                       # Claim fee threshold
    "0x7d0c0380fc3b999d5726da0c9c2f986b972ba597eafa903e7bcebcd69f28ffd", # Main token
]
"ponzi_land-actions" = [
    "128000000000000000000",                                              # Start price (low)
    "0",                                                                  # Start price (high)
    "1000000000000000000",                                                # Floor price (low)
    "0",                                                                  # Floor price (high)
    "0x0444a09d96389aa7148f1aada508e30b71299ffe650d9c97fdaae38cb9a23384", # Ekubo core address (unused)
    "0x7d0c0380fc3b999d5726da0c9c2f986b972ba597eafa903e7bcebcd69f28ffd", # Main token
]

# External contract deployment - Liquidity Reinjector (non-Dojo contract)
[[external_contracts]]
contract_name = "LiquidityReinjector"
salt = "1"
constructor_data = [
    "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"  # Owner address (same as account_address from [env])
]

