[package]
cairo-version = "=2.12.2"
name = "ponzi_land"
version = "1.4.0"
edition = "2023_01"
license = "MIT"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                    # scarb run migrate
spawn = "sozo execute ponzi_land-actions spawn --wait"    # scarb run spawn
move = "sozo execute ponzi_land-actions move -c 1 --wait" # scarb run move

[dependencies]
starknet = "=2.12.2"

dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.1" }
dojo_cairo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.1" }


openzeppelin_token = "1.0.0" 
openzeppelin_security = "1.0.0"
ekubo = { git = "https://github.com/EkuboProtocol/abis", rev = "edb6de8c9baf515f1053bbab3d86825d54a63bc3" }
game_components_minigame = { git = "https://github.com/ZackAmes/game-components", rev = "2af3d18e3874be5a147e79e81aff8eb23658aa3b"}



[profile.sepolia]

[profile.mainnet]

[profile.mainnet-test]

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
sierra = true
casm = true

[dev-dependencies]
cairo_test = "=2.12.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.1" }
