world_address = "0x7e3e8b4eab233129d0f96ce07494a6f5bcfa728bc0081dbc2a81cd28e406228"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"
explorer = false

[events]
raw = true

[sql]
historical = [
    "ponzi_land-AddressAuthorizedEvent",
    "ponzi_land-AddressRemovedEvent",

    "ponzi_land-AuctionFinishedEvent",
    "ponzi_land-LandBoughtEvent",
    "ponzi_land-LandNukedEvent",

    "ponzi_land-NewAuctionEvent",
    "ponzi_land-RemainingStakeEvent",

    "ponzi_land-VerifierUpdatedEvent",

    "ponzi_land-Land",
    "ponzi_land-LandStake",


    "ponzi_land-Quest",
    "ponzi_land-QuestDetails",
    "ponzi_land-PlayerRegistrations",
    "ponzi_land-QuestCounter",
    "ponzi_land-QuestDetailsCounter",
    "ponzi_land-GameMetadata",
    "ponzi_land-GameCounter",
    "ponzi_land-TokenMetadata",
    "ponzi_land-Score",
    "ponzi_land-Settings",
    "ponzi_land-SettingsDetails",
    "ponzi_land-SettingsCounter",
]


[indexing]
contracts = [
    "erc20:0x07820a11cf65ed89a86ca396db5f6f7362253b990015c9ac5c5ad8f277716901", # pltSTRK
    "erc20:0x009070eac7b5791d1c3a37fa5735e3c9be55004400543f43cbb8912d835157d5", # pltLORDS
    "erc20:0x01544000184b0d667f63005fee5ef39bc0514565b5580291256456db5d9e08f3", # pltETH
    "erc20:0x02758ab836d286e13c89a434613a8d47f6e8cc20f0d2a74ae111a16553905801", # pltPAPER
    "erc20:0x05aa6c0482d24e017d3e177a7df96528e75c158476559f1012b2e944d28e8903", # pltBROTHER
    "erc20:0x029b0b4a0b3c08744ba46f38a2e4a455c48c6b8c44fff902e45188eb6b655a0d", # pltPAL
]
