export let devsettings = $state({
  frustumPadding: 2,
  cameraControlsLeftClick: 2,
  cameraControlsRightClick: 2,
  CameraControlsWheel: 0b100000,
  billboarding: false,
  randomUpdates: false, // Enable/disable random land updates
  minRandomUpdates: 10,
  maxRandomUpdates: 20,
  nukeRate: 0.5,
  updateInterval: 1000,
  showRoads: false,
  showBuildings: false,
  showBiomes: false,
  showCoins: false,
  showLandOverlay: false,
  showGrid: true,
  showUI: false,
  showNukes: false,
  showFog: false,
  showOwnerIndicator: false,
  showNukeTimes: false,
  showArtLayer: false,
  artLayerOpacity: 0.7,
  showOwnedLandOverlay: false,
});
