export let devsettings = $state({
  frustumPadding: 2,
  cameraControlsLeftClick: 2,
  cameraControlsRightClick: 2,
  CameraControlsWheel: 0b100000,
  billboarding: false,
  randomUpdates: true, // Enable/disable random land updates
  minRandomUpdates: 10,
  maxRandomUpdates: 20,
  nukeRate: 0.5,
  updateInterval: 1000,
  showRoads: true,
  showBuildings: true,
  showBiomes: true,
  showCoins: true,
  showLandOverlay: true,
  showGrid: true,
  showUI: true,
  showNukes: true,
  showFog: false,
  showOwnerIndicator: true,
  showNukeTimes: true,
});
