import { MAX_CLAIM_ALL_COUNT } from '$lib/flags';

export let devsettings = $state({
  frustumPadding: 2,
  claimAllCount: MAX_CLAIM_ALL_COUNT,
  cameraControlsLeftClick: 2,
  cameraControlsRightClick: 2,
  CameraControlsWheel: 0b100000,
  billboarding: false,
  randomUpdates: false, // Enable/disable random land updates
  minRandomUpdates: 10,
  maxRandomUpdates: 20,
  nukeRate: 0.5,
  updateInterval: 1000,
  showRoads: true,
  showBiomes: true,
  showBuildings: true,
  showCoins: true,
  showLandOverlay: true,
  showRatesOverlay: true,
  showGrid: false,
  showUI: true,
  showNukes: true,
  showOwnerIndicator: true,
  showNukeTimes: false,
  showArtLayer: false,
  artLayerOpacity: 1,
  showHeatmap: false,
  showClouds: true,
  multiLandInfo: false,
});
