name: Account Package Checks

on:
  pull_request:
    paths:
      - "packages/account/**"
      - ".github/workflows/account-package-checks.yml"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "v1.3.0"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('packages/account/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        working-directory: packages/account
        run: bun install

      - name: Build dependency (ui)
        working-directory: packages/ui
        run: bun run build

      - name: Build package
        working-directory: packages/account
        run: bun run build

      - name: Verify build output
        working-directory: packages/account
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build failed: dist/index.js not found"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "Build failed: dist/index.d.ts not found"
            exit 1
          fi
          echo "Build succeeded: Required files found in dist/"
