name: client-formatting

on:
  push:
    branches:
      - "main"
  pull_request: {}

permissions:
  contents: read
  packages: read

jobs:
  client-formatting:
    name: Validate client formatting
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "v1.1.45"
      - name: Setup bunfig.toml
        working-directory: ./client
        run: |
          echo "[install]" >> ./bunfig.toml
          echo "registry = \"https://registry.npmjs.org\"" >> ./bunfig.toml
          echo "[install.scopes]" >> ./bunfig.toml
          echo "\"@runelabsxyz\" = { token = \"${{ secrets.GITHUB_TOKEN }}\", url = \"https://npm.pkg.github.com/\" }" >> ./bunfig.toml
          cat ./bunfig.toml # Debug output to check file contents

      - name: Install dependencies
        working-directory: ./client
        run: bun install --frozen-lockfile

      - name: Check formatting
        working-directory: ./client
        run: bun prettier --check .
