name: sepolia-deployment

on:
  push:
    branches:
      - "main"
      - "target/*"
  # Cloudflare handles preview environments pretty well:
  pull_request:
    branches:
      - "main"
      - "target/*"

permissions:
  contents: read
  deployments: write
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  packages: read

jobs:
  sepolia-deployment:
    name: Deploy UI to cloudflare (Sepolia)
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - id: setup-dojo
        uses: runelabsxyz/setup-dojo@main
        with:
          version: "v1.0.12"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "v1.1.45"

      - name: Setup bunfig.toml
        working-directory: ./client
        run: |
          echo "[install]" >> ./bunfig.toml
          echo "registry = \"https://registry.npmjs.org\"" >> ./bunfig.toml
          echo "[install.scopes]" >> ./bunfig.toml
          echo "\"@runelabsxyz\" = { token = \"${{ secrets.GITHUB_TOKEN }}\", url = \"https://npm.pkg.github.com/\" }" >> ./bunfig.toml
          cat ./bunfig.toml # Debug output to check file contents

      - name: Install dependencies
        working-directory: ./client
        run: bun install --frozen-lockfile

      - name: Build frontend for sepolia
        run: bun run build:sepolia
        working-directory: ./client
        env:
          LAYERSWAP_TOKEN: ${{ secrets.LAYERSWAP_TOKEN }}
          BYPASS_TOKEN: "" # If you want to enable the maintenance wall:  ${{ secrets.BYPASS_TOKEN }}
          # Force the auto bundler to prepare for cloudflare (otherwise it does weird things)
          CF_PAGES: "1"

      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v2.3.2
        id: pages
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: ./client/.svelte-kit/cloudflare
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: PonziLand ${{ (github.ref == 'refs/heads/main' && '(Production)') || '(Preview)' }}
