name: Client - Formatting

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read
  packages: read

jobs:
  slot-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          echo "[install.scopes]" > ~/.bunfig.toml
          echo "\"@runelabsxyz\" = { token = \"${{ secrets.GITHUB_TOKEN }}\", url = \"https://npm.pkg.github.com\" }" >> ~/.bunfig.toml
          cat ~/.bunfig.toml # Debug output to check file contents
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "======"
          cat ~/.npmrc # Debug output to check file contents

      - name: Install dependencies
        working-directory: ./client
        run: bun install --frozen-lockfile --verbose

      - name: Check formatting
        working-directory: ./client
        run: bun prettier --check .
