name: contract-testing

on:
  push:
    branches:
      - "main"
  pull_request: {}

permissions:
  contents: read

jobs:
  contract-testing:
    name: Run contract tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - id: setup-dojo
        uses: runelabsxyz/setup-dojo@main
        with:
          version: "v1.4.0"

      - name: Build contract
        working-directory: ./contracts
        run: sozo build

      - name: Test contract (standard)
        if: github.event_name != 'release'
        working-directory: ./contracts
        run: sozo test

      - name: Test contract (ignored tests for release)
        if: github.event_name == 'release'
        working-directory: ./contracts
        run: sozo test --ignored

      - name: Test contract (non-ignored tests for release)
        if: github.event_name == 'release'
        working-directory: ./contracts
        run: sozo test
